---

resources:
- name: source-app
  type: git
  source: {uri: ((source-app))}

- name: pipelines
  type: git
  source: {uri: ((pipelines))}


jobs:
- name: build-and-push-app
  public: true
  plan:
  - get: source-app
    trigger: true
  - get: pipelines
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: ggoksu/pack-image
          username: ((username))
          password: ((password))
          tag: 0.1.0
      inputs:
      - name: source-app
      - name: pipelines
      outputs:
      - name: some-files
      run:
        path: pipelines/build/build-image.sh
      params:
        APP: source-app
        BUILDER: ((builder))
        TAG: 1.0.0
        REPOSITORY: ((repository))