---

resources:
- name: ((app-name))
  type: git
  source: {uri: ((source-app))}

- name: pipelines #pipelinelarin alinacagi repo
  type: git
  source: {uri: ((pipelines))}

- name: registry
  type: docker-image
  source:
    repository: ((registry))/((project))/((app-name))
    username: ((username))
    password: ((password))
    tag: ((tag))
    insecure_registries: [((registry))]

jobs:
- name: build-and-push-app
  public: true
  plan:
  - get: ((app-name))
    trigger: true
  - get: pipelines
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: ggoksu/pack-image
          tag: 0.1.0
      inputs:
      - name: ((app-name))
      - name: pipelines
      outputs:
      - name: image
      run:
        path: pipelines/build/build-image.sh
      params:
        APP: ((app-name))
        BUILDER: ((builder)) # cloudfoundry/cnb:bionic
        TAG: ((tag)) # harbor'da kullanilacak tag
        REGISTRY: ((registry)) #harbor repo
        PROJECT: ((project)) # harbor proje ismi
  - put: registry
    params:
      load_file: image/image.tar  
      load_repository: ((registry))/((project))/((app-name))
      load_tag: ((tag))
      tag_file: image/tag
      get_params: {skip_download: true}
- name: deploy-to-pks
  public: true
  plan:
  - get: pipelines
  - get: registry
    params: {skip_download: true}
    trigger: true
    passed: [build-and-push-app]
  - task: deploy
    file: pipelines/deploy/task.yml
    params:
      ENVIRONMENT: ((namespace))
      PKS_CLUSTER_NAME: ((pks_cluster_name))
      PKS_API_ENDPOINT: ((pks_api_endpoint))
      PKS_USERNAME: ((pks_username))
      PKS_PASSWORD: ((pks_password))
      DOCKER_REGISTRY_SERVER: ((registry))
      DOCKER_REGISTRY_USERNAME: ((username))
      DOCKER_REGISTRY_PASSWORD: ((password))
      DEPLOYMENT_MANIFEST: ((deployment_manifest)) 
      #VSPHERE_STORAGE_CLASS: ((vsphere_storage_class))