---

resources:
- name: source-app
  type: git
  source: {uri: ((source-app))}

- name: pipelines
  type: git
  source: {uri: ((pipelines))}

- name: registry
  type: registry-image
  source:
    repository: ((repository))
    username: ((username))
    password: ((password))

jobs:
- name: build-and-push-app
  public: true
  plan:
  - get: source-app
    trigger: true
  - get: pipelines
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: ggoksu/pack-image
          tag: 0.1.0
      inputs:
      - name: source-app
      - name: pipelines
      outputs:
      - name: image
      run:
        path: pipelines/build/build-image.sh
      params:
        APP: source-app
        BUILDER: ((builder)) # cloudfoundry/cnb:bionic
        #TAG: 1.0.0 # harbor'da kullanilacak tag
        #REPOSITORY: ((repository)) #harbor repo
        #PROJECT: ((project)) # harbor proje ismi
        #HARBOR_USER: ((harbor-user))
        #HARBOR_PASS: ((harbor-pass))
- name: push-to-harbor
  public: true
  plan:
    - get: pipelines
      passed: [build-and-push-app]
      trigger: true
    - task: deploy
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: busybox
        inputs:
        - name: image
        run:
          path: pipelines/build/build-image.sh
    - put: registry
        
      