---

resources:
- name: ((app-name))
  type: git
  source: {uri: ((source-app))}

- name: pipelines
  type: git
  source: {uri: ((pipelines))}

- name: registry
  type: docker-image
  source:
    repository: ((registry))/((project))/((app-name))
    username: ((username))
    password: ((password))
    insecure_registries: [((registry))]

jobs:
- name: build-and-push-app
  public: true
  plan:
  - get: ((app-name))
    trigger: true
  - get: pipelines
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: 
          repository: ggoksu/pack-image
          tag: 0.1.0
      inputs:
      - name: ((app-name))
      - name: pipelines
      outputs:
      - name: image
      run:
        path: pipelines/build/build-image.sh
      params:
        APP: ((app-name))
        BUILDER: ((builder)) # cloudfoundry/cnb:bionic
        TAG: 1.0.0 # harbor'da kullanilacak tag
        REGISTRY: ((registry)) #harbor repo
        PROJECT: ((project)) # harbor proje ismi
        #HARBOR_USER: ((harbor-user))
        #HARBOR_PASS: ((harbor-pass))
  - put: registry
    params:
      load_file: image/image.tar  
      load_repository: ((registry))/((project))/((app-name))