---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: harbor.sandbox.demo1.pocs.pcfs.io/build-images/automatio-tools
    insecure_registries: [harbor.sandbox.demo1.pocs.pcfs.io]

inputs:
- name: pipelines
- name: registry

run:
  path: pipelines/deploy/task.sh