apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
  selector:
    app: web-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
        version: v1
    spec:
      containers:
        - name: web-app
          image: $IMAGE_REPOSITORY:$VERSION
          ports:
            - containerPort: 8080